import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";

export function TermsPage() {
  return (
    <div className="min-h-screen bg-ds-bg-primary">
      <Header />
      <div className="pt-24 pb-16">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold text-ds-text-primary mb-2">Terms of Service</h1>
          <p className="text-sm text-ds-text-muted mb-10">Last updated: January 2026</p>

          <div className="space-y-8 text-sm text-ds-text-secondary leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-ds-text-primary mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing and using AI Accountant Adviser ("the Service"), you accept and agree to be
                bound by these Terms of Service. If you do not agree, do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-ds-text-primary mb-3">2. AI-Generated Advice Disclaimer</h2>
              <p>
                All advice, strategies, and analysis provided by AI Accountant Adviser is generated by
                artificial intelligence and is provided for <strong className="text-ds-text-primary">informational purposes only</strong>.
                It does not constitute professional accounting, tax, legal, or financial advice. The
                Service is not a substitute for professional consultation with a qualified accountant
                or tax adviser.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-ds-text-primary mb-3">3. Limitation of Liability</h2>
              <p>
                AI Accountant Adviser and its operators accept <strong className="text-ds-text-primary">no responsibility</strong> for
                any financial decisions, actions, or consequences resulting from the use of the Service.
                Users are solely responsible for verifying all advice and making their own informed
                decisions.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-ds-text-primary mb-3">4. Professional Verification</h2>
              <p>
                We strongly recommend that all advice and strategies generated by the Service be
                verified by a licensed accountant, chartered tax adviser (CTA), or other qualified
                professional before being acted upon.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-ds-text-primary mb-3">5. Payment Terms</h2>
              <p>
                The initial consultation costs £10 (GBP) and includes up to 50 follow-up questions.
                Additional question packs (50 questions for £50) are available. All payments are
                processed securely via Stripe. Payments are non-refundable once the consultation has begun.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-ds-text-primary mb-3">6. Data Handling</h2>
              <p>
                Documents uploaded to the Service are processed for analysis purposes and stored
                encrypted on secure cloud infrastructure (AWS). We handle all data in accordance with
                our Privacy Policy and applicable data protection legislation including UK GDPR.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-ds-text-primary mb-3">7. Cookie Policy</h2>
              <p>
                The Service uses essential cookies for authentication and session management. We may
                also use analytical cookies to improve the Service. You can manage your cookie
                preferences through the cookie consent banner.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-ds-text-primary mb-3">8. Intellectual Property</h2>
              <p>
                You retain ownership of all documents you upload. The strategies and analysis generated
                by the Service are provided for your personal or business use. The underlying AI models,
                algorithms, and platform remain the intellectual property of AI Accountant Adviser.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-ds-text-primary mb-3">9. Governing Law</h2>
              <p>
                These Terms shall be governed by and construed in accordance with the laws of England
                and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts
                of England and Wales.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-ds-text-primary mb-3">10. Contact</h2>
              <p>
                For questions about these Terms, please contact us at{" "}
                <a href="mailto:support@aiaccountant.co.uk" className="text-ds-text-accent hover:underline">
                  support@aiaccountant.co.uk
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
