import { Modal } from "@/components/ui/Modal";

interface TermsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function TermsModal({ isOpen, onClose }: TermsModalProps) {
  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Terms of Service" size="lg">
      <div className="max-h-[60vh] overflow-auto space-y-4 text-sm text-ds-text-secondary leading-relaxed pr-2">
        <p>
          By using AI Accountant Adviser, you agree to the following terms and conditions. Please read
          them carefully before proceeding.
        </p>
        <h3 className="text-ds-text-primary font-semibold">1. AI-Generated Advice Disclaimer</h3>
        <p>
          All advice provided by AI Accountant Adviser is generated by artificial intelligence and is
          for informational purposes only. It does not constitute professional accounting, tax, or
          financial advice.
        </p>
        <h3 className="text-ds-text-primary font-semibold">2. No Responsibility</h3>
        <p>
          AI Accountant Adviser accepts no responsibility for any actions taken based on the advice
          provided. Users are solely responsible for their financial decisions.
        </p>
        <h3 className="text-ds-text-primary font-semibold">3. Professional Verification</h3>
        <p>
          All advice should be verified by a licensed accountant or qualified tax professional before
          being acted upon.
        </p>
        <h3 className="text-ds-text-primary font-semibold">4. Data Handling</h3>
        <p>
          Documents uploaded are processed securely and stored encrypted on AWS. We retain data for
          the duration of your consultation. See our Privacy Policy for full details.
        </p>
        <h3 className="text-ds-text-primary font-semibold">5. Payment</h3>
        <p>
          Payments are non-refundable once the consultation has begun. All payments are processed
          securely via Stripe.
        </p>
      </div>
    </Modal>
  );
}
